### ISSUE TITLE
Make the link to the documentation easier to find.

### ISSUE THREAD

**Issue by adamltyson** [padster/pyNeuroTrace#12]
The documentation is key for anyone new to the software, and I think the only link is the badge? It would be helpful to make this link really obvious, maybe by:
- Adding it as the repo URL in the sidebar
- Adding it in the README text

Apologies if I missed it somewhere.

**Comment by padster** [comment]
Good suggestions - 

Documentation link added to sidebar:
![sidebar](https://github.com/user-attachments/assets/d80db7f5-46a2-4242-8214-b48392dfca18)

And README:
![readme](https://github.com/user-attachments/assets/0a0312df-b3f3-43f0-bc13-80bca9c440c6)
