### ISSUE TITLE
gpu functionality and performance

### ISSUE THREAD

**Issue by danielmk** [padster/pyNeuroTrace#7]
Related to https://github.com/openjournals/joss-reviews/issues/6877

I was able to install with cupy and I would like to confirm the GPU performance claim. Would it be possible to get the data that was used in the paper (Figure4)? And the code that was used? Thank you.

**Comment by Peter-Hogg** [comment]
Yes, I'll add a notebook to the repo soon. I'm currently traveling so it might be a day or two.

**Comment by Peter-Hogg** [comment]
Sorry for the delay. I was hoping to be able to work on this during my trip, but my schedule was too busy. I've added the code used to generate the figures in the manuscript to the examples folder in a new Jupyter Notebook.
