### ISSUE TITLE
import missing in example notebook

### ISSUE THREAD

**Issue by stephenlenzi** [padster/pyNeuroTrace#8]
In the example notebook _, _ = plotIntensity(rawTimeSeries, hz, title='Cal590 Raw Traces') fails because plotIntensity is not imported.

**Comment by stephenlenzi** [comment]
Related to review: https://github.com/openjournals/joss-reviews/issues/6877

**Comment by Peter-Hogg** [comment]
I've corrected the typo that caused the issue. The notebook should be working correctly now.
