### ISSUE TITLE
Comparison of the tool with other commonly used packages

### ISSUE THREAD

**Issue by stephenlenzi** [padster/pyNeuroTrace#9]
Related to review: https://github.com/openjournals/joss-reviews/issues/6877 

Personally I'd like to see a bit more detail about the state of the field and where this tool fits into the wider landscape. For example there are other softwares for dealing with calcium imaging data (e.g. Suite2P, CaImAn) and although they have a slightly different focus, they do seem to have overlapping functionality particularly in terms of event detection and estimating df/f. I think it is important to highlight how pyNeuroTrace compares and/or complements these and other existing pipelines.

On a (possibly) related note, the statement of need in paper.md is different to paper.pdf (is the paper.md more up to date?). The pdf doesn't mention other softwares explicitly at all, whereas the .md does highlight a couple of examples.

**Comment by stephenlenzi** [comment]
Just to follow up on the last point - I was reading the paper.pdf instead of the draft MS (assuming they were the same, but they're not.. my mistake). I see that the statement of need in the draft MS does indeed mention alternative softwares.

**Comment by danielmk** [comment]
The draft version I have (10.21105.joss.06877.pdf) references CaImAn but does not reference Suite2P. I think it would be important to reference Suite2P and explain the gap that the JOSS submission is filling in Suite2P functionality.

**Comment by Peter-Hogg** [comment]
I'll review Suite2P's current functionality. The last time I checked, it didn't calculate dF/F. If that is still the case, I'll add some comments to the manuscript about how this library fills that gap. 

@stephenlenzi  I think the paper.pdf got out of sync with the paper.md because I forgot to regenerate the pdf version with Pandoc before pushing after editing the manuscript. I'll try not to do that again.

**Comment by Peter-Hogg** [comment]
I have added a brief statement referencing how pyNeuroTrace fills a gap in Suite2P's functionality. I can expand this further in the manuscript is needed
